service: my-app

provider:
  name: aws
  region: eu-west-1
  runtime: nodejs14.x

functions:
  app:
    handler: dist/main.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
